project:
  type: website
  output-dir: docs

website:
  title: "Cassie Liu"
  navbar:
    right:
      - href: index.qmd
        text: Home
      #- text: "CV"
      #  href: pdfs/Jiwon_resume.pdf
      - icon: github
        href: https://github.com/Cassieliu77
      - icon: envelope
        href: cassieliu.liu@mail.utoronto.ca
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

